const http = require('http');
const dns = require('dns').promises;
const { URL } = require('url');
const PORT = Number(process.env.PORT || 10000), MAX_BODY=256*1024, TIMEOUT=30000, sessions=new Map();
const json=(res,code,body,headers={})=>{res.writeHead(code,{'content-type':'application/json; charset=utf-8',...headers});res.end(JSON.stringify(body))};
const err=(code,message)=>({error:code,message});
async function safeEndpoint(raw){let u;try{u=new URL(raw)}catch{throw Object.assign(new Error('Invalid endpoint'),{code:'INVALID_ENDPOINT'})}if(u.protocol!=='https:'||u.username||u.password)throw Object.assign(new Error('HTTPS endpoint required'),{code:'INVALID_ENDPOINT'});const h=u.hostname.toLowerCase();if(['localhost','ip6-localhost'].includes(h)||h.endsWith('.localhost')||h.endsWith('.local'))throw Object.assign(new Error('Private/local destinations are not allowed'),{code:'INVALID_ENDPOINT'});for(const x of await dns.lookup(h,{all:true})){if(/^(10\\.|127\\.|169\\.254\\.|192\\.168\\.|172\\.(1[6-9]|2\\d|3[0-1])\\.|::1$|fc|fd|fe80:)/i.test(x.address))throw Object.assign(new Error('Private/local destinations are not allowed'),{code:'INVALID_ENDPOINT'})}return u.toString()}
async function remote(url,payload,sid){const ac=new AbortController(),t=setTimeout(()=>ac.abort(),TIMEOUT);try{const headers={'content-type':'application/json','accept':'application/json, text/event-stream'};if(sid)headers['mcp-session-id']=sid;const r=await fetch(url,{method:'POST',headers,body:JSON.stringify(payload),signal:ac.signal,redirect:'manual'});if([301,302,303,307,308].includes(r.status))throw Object.assign(new Error('Redirects are not allowed'),{code:'CONNECT_FAILED'});const text=await r.text();if(!r.ok)throw Object.assign(new Error(text.slice(0,1000)||('HTTP '+r.status)),{code:r.status===401||r.status===403?'AUTH_REQUIRED':'REMOTE_TOOL_ERROR'});let data;try{data=JSON.parse(text)}catch{throw Object.assign(new Error('Remote MCP returned non-JSON response'),{code:'REMOTE_TOOL_ERROR'})}return {data,sessionId:r.headers.get('mcp-session-id')||sid}}catch(e){if(e.name==='AbortError')throw Object.assign(new Error('Remote MCP timed out'),{code:'TIMEOUT'});throw e}finally{clearTimeout(t)}}
async function connect(endpoint){const id=Math.random().toString(36).slice(2,8),r=await remote(endpoint,{jsonrpc:'2.0',id:1,method:'initialize',params:{protocolVersion:'2025-06-18',capabilities:{},clientInfo:{name:'mcp-bridge',version:'0.1.0'}}});const s={id,endpoint,sessionId:r.sessionId,serverInfo:r.data?.result?.serverInfo||null,connectedAt:new Date().toISOString()};sessions.set(id,s);await remote(endpoint,{jsonrpc:'2.0',method:'notifications/initialized',params:{}},s.sessionId).catch(()=>{});return s}
const call=(s,method,params)=>remote(s.endpoint,{jsonrpc:'2.0',id:Date.now(),method,params},s.sessionId);
function readBody(req){return new Promise((resolve,reject)=>{let n=0,b='';req.on('data',c=>{n+=c.length;if(n>MAX_BODY){reject(Object.assign(new Error('Request too large'),{code:'INVALID_ARGUMENTS'}));req.destroy()}else b+=c});req.on('end',()=>{try{resolve(b?JSON.parse(b):{})}catch{reject(Object.assign(new Error('Invalid JSON'),{code:'INVALID_ARGUMENTS'}))}});req.on('error',reject)})}
http.createServer(async(req,res)=>{if(req.method==='GET'&&req.url==='/health')return json(res,200,{ok:true,service:'mcp-bridge',version:'0.1.0'});if(req.method!=='POST'||req.url!=='/mcp')return json(res,404,{error:'NOT_FOUND',message:'Use POST /mcp'});try{const x=await readBody(req),m=x.method,p=x.params||{};if(m==='connect_mcp'){const s=await connect(await safeEndpoint(p.endpoint));return json(res,200,{jsonrpc:'2.0',id:x.id,result:{connection_id:s.id,endpoint:s.endpoint,server_info:s.serverInfo}})}const s=sessions.get(p.connection_id);if(!s)return json(res,400,{jsonrpc:'2.0',id:x.id,error:err('CONNECT_FAILED','Unknown connection_id')});if(m==='discover_mcp_tools'){const r=await call(s,'tools/list',{});return json(res,200,{jsonrpc:'2.0',id:x.id,result:r.data?.result||r.data})}if(m==='call_mcp_tool'){if(!p.tool_name)return json(res,400,{jsonrpc:'2.0',id:x.id,error:err('INVALID_ARGUMENTS','tool_name is required')});const r=await call(s,'tools/call',{name:p.tool_name,arguments:p.arguments||{}});return json(res,200,{jsonrpc:'2.0',id:x.id,result:r.data?.result||r.data})}if(m==='mcp_status')return json(res,200,{jsonrpc:'2.0',id:x.id,result:{connections:[...sessions.values()].map(s=>({connection_id:s.id,endpoint:s.endpoint,server_info:s.serverInfo,connected_at:s.connectedAt}))}});if(m==='disconnect_mcp'){sessions.delete(p.connection_id);return json(res,200,{jsonrpc:'2.0',id:x.id,result:{disconnected:true}})}return json(res,400,{jsonrpc:'2.0',id:x.id,error:err('INVALID_ARGUMENTS','Unknown method')})}catch(e){return json(res,400,{jsonrpc:'2.0',id:null,error:err(e.code||'REMOTE_TOOL_ERROR',e.message||'Request failed')})}}).listen(PORT,()=>console.log('mcp-bridge listening on '+PORT));